#!/bin/bash
#
#  Copyright (C) 2019, lothrond <lothrond@posteo.us>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <https://www.gnu.org/licenses/>.

## BEGIN DEFAULT ENVIRONMENT

[ $LUPDATE_LIBDIR ] || \
    LUPDATE_LIBDIR=/usr/local/lib/lupdate

[ $LUPDATE_GITDIR ] || \
    LUPDATE_GITDIR=( ~/source )

## END DEFAULT ENVIRONMENT

# suppliment root with sudo
if [ $UID -ne 0 ]; then
    ssu=sudo
fi

# colors
col0="\e[31m"
col1="\e32m"
res="\e0m"

# return values
RET1="${col0}Failed${res}"
RET0="${col1}Successful${res}"

# set default return value to failed.
# (for ctrl-c interrrupts, etc)
ret=$RET1

#---------------------------------------------------------------------------
# For every file type, source functions for operations, perform operations,
# and then return user value (success/fail).
#---------------------------------------------------------------------------

if ${LUPDATE_LIBDIR}/apt_update.sh; then
    if ${LUPDATE_LIBDIR}/flatpak_update.sh; then
        if ${LUPDATE_LIBDIR}/git_update.sh; then
            if ${LUPDATE_LIBDIR}/pip_update.py; then
# check return values
                ret=$RET0
            fi
        fi
    fi
fi

echo -e "\nUpgrade ${ret}"
exit $?
